apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  labels:
    app: shop
  namespace: shop-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: arshinkinda/shop-origin:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
  namespace: shop-namespace
spec:
  selector:
    app: shop
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8082
      nodePort: 32487
