apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
  namespace: product-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: arshinkinda/product-origin:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-namespace
spec:
  selector:
    app: product
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8082
      nodePort: 32487
