spring:
  application:
    name: order
server:
  port: ${DISCOVERED_SERVICE_PORT:8084}
logging:
  level:
    root: INFO
app:
  api:
    endpoint:
      order:
        checkout: /v1/order/checkout
  aws:
    region: ${AWS_REGION:us-east-1}
    queueName: ${AWS_SQS_QUEUE:DemoQueue}