spring:
  application:
    name: order
server:
  port: ${DISCOVERED_SERVICE_PORT:8084}
logging:
  level:
    root: INFO
app:
  api:
    endpoint:
      order:
        checkout: /v1/order/checkout
  aws:
    region: ${AWS_REGION:us-east-1}
    queueName: ${AWS_SQS_QUEUE:OrderQueue}
    endpointUri: ${AWS_ENDPOINT_URI:https://vpce-080b486b2bfb75c7f-9ai3n508.sqs.us-east-1.vpce.amazonaws.com}