spring:
  application:
    name: product
server:
  port: ${DISCOVERED_SERVICE_PORT:8082}
logging:
  level:
    root: INFO
app:
  api:
    endpoint:
      product:
        retrieve_by_id: /v1/product/{id}
        create_product: /v1/product
