spring:
  application:
    name: cart
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/shop_cart}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:rws_postgres}
    password: ${DB_PASSWORD:!rws_postgres!}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
server:
  port: ${DISCOVERED_SERVICE_PORT:8083}
logging:
  level:
    root: INFO
app:
  api:
    endpoint:
      cart:
        retrieve:
          byCartId: /v1/cart/{cartId}
        delete:
          byCartId: /v1/cart/{cartId}
        update:
          putDefaultProducts: /v1/cart/populate/{cartId}
cart:
  default:
    products:
      - apple
      - pear
      - orange
      - TV-set

