spring:
  application:
    name: cart
  datasource:
    url: ${DB_URI}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
#    use_sql_comments: true
#    format_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
server:
  port: ${DISCOVERED_SERVICE_PORT:8083}
logging:
  level:
    root: INFO