spring:
  application:
    name: cart
  datasource:
    url: ${DB_URI}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
server:
  port: ${DISCOVERED_SERVICE_PORT:8083}
logging:
  level:
    root: INFO